/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DataView: typeof import('./src/components/DataView.vue')['default']
    DeviceCard: typeof import('./src/components/DeviceCard.vue')['default']
    DeviceModal: typeof import('./src/components/DeviceModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
