/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DataItem: typeof import('./src/components/DataItem.vue')['default']
    DataView: typeof import('./src/components/DataView.vue')['default']
    DetailedDataView: typeof import('./src/components/DetailedDataView.vue')['default']
    DeviceCard: typeof import('./src/components/DeviceCard.vue')['default']
    DeviceModal: typeof import('./src/components/DeviceModal.vue')['default']
    SavingsBarGraph: typeof import('./src/components/SavingsBarGraph.vue')['default']
  }
}
